### ISSUE TITLE
Example lists "seed" as mandatory attribute

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/terraform-provider-gardener#25]
**Description**
The example on the main readme lists the "seed" attribute as something mandatory, indeed the customer cannot know an appropriate value for it. The gardener example for customers also do not mention it. I guess it must be an optional attribute and not listed in the readme.

**Expected result**
Example does not mention the attribute as I don't know the value to enter

**Actual result**
The attribute is listed

**Steps to reproduce**
Go to https://github.com/kyma-incubator/terraform-provider-gardener/blob/master/README.md

**Comment by clebs** [comment]
After discussing it with the gardener team, we decided that we will completely remove the seed property from the spec, since gardener can assign a seed based on load and current capacity, which is better than setting it on our own.
The tasks for that are:
- Remove spec from `terraform-gardener-provider` and adapt examples.
- Release a new version of the provider
- Update and adapt `Hydroform`
- Update and adapt the Kyma CLI
